//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalog()
        {
            this.orderitems = new HashSet<orderitem>();
        }
    
        public int CatalogItemID { get; set; }
        public int CategoryID { get; set; }
        public int MakerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int InStockNum { get; set; }
        public string OrigCountry { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public Nullable<int> Warranty { get; set; }
        public int ConditionID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderitem> orderitems { get; set; }
    }
}
