//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSPOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderitem
    {
        public int OrderID { get; set; }
        public int CatalogItemID { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual catalog catalog { get; set; }
        public virtual order order { get; set; }
    }
}
